# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 175c3132ec0fa0d7989091c3421eaa77948918fa1801c6398af9ae5540d2839095bb7d22b001f900a17b9d0e0f430bfbe9073b48cf5a1bbe1b552f830fb46ad5

test:
  secret_key_base: c940e58dca5d5f58e2f7a117a55853bf5290edb3dc8a5aece3d488ca28145d29873ca8138edcf7af6304700b80060e990e3a8f5a03dad6b3c4c881245d7b0a10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
